/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  backFastapi: [
    {
      type: 'category',
      label: 'Backend with FastAPI',
      items: [
        { type: 'autogenerated', dirName: 'graphql/back-fastapi' }
      ],
    },
  ],

  dataScala: [
    {
      type: 'category',
      label: 'Data Management with Scala',
      items: [
        { type: 'autogenerated', dirName: 'graphql/data-scala' }
      ],
    },
  ],

  backGo: [
    {
      type: 'category',
      label: 'Backend with Golang',
      items: [
        { type: 'autogenerated', dirName: 'graphql/back-go' }
      ],
    },
  ],
  

};

module.exports = sidebars;
